odb = require 'orientdb'

for _, socket_lib in pairs({'socket'}) do
  describe('connect over #'..socket_lib, function()
    it('check client parameters', function()
      assert.has.errors(function() odb.new('localhost', 2424, 'not_a_lib') end)
      assert.has.errors(function() odb.new('localhost', 'not a port', socket_lib) end)
      assert.has.errors(function() odb.new(nil, 2424, socket_lib) end)
    end)
    it('create client', function()
      assert.has_no.errors(function() odb.new('localhost', 2424, socket_lib) end)
    end)
    it('connect', function()
      assert.truthy(function()
        local client = odb.new('localhost', 2424, socket_lib)
        return client:connect('root', 'root')
      end)
    end)
  end)
  describe('graph over #'..socket_lib, function()
    local client = odb.new('localhost', 2424, socket_lib)
    client:connect('root', 'root')
    it('list databases', function()
      print(client:db_list())
      assert.same(client:db_list(), {'animals'})
    end)
    it('open database', function()
      assert.thruthy(client:db_open('animals', 'graph', 'root', 'root'))
    end)
    client:disconnect()
  end)
end
